spring: 
  application: 
    name: config-server
  profiles: 
    active: native
  cloud: 
    config: 
      server: 
        health:
          enabled:  false
        native:
          searchLocations: classpath:/user-service,classpath:/prod-service,classpath:/order-service,classpath:/api-gateway

server: 
  port: 2222
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/  

  


