spring: 
  application: 
    name: config-server
  profiles: 
    active: native
  cloud: 
    config: 
      server: 
        health:
          enabled:  false
        native:
          searchLocations: classpath:/shared,classpath:/shared/user-service,classpath:/shared/prod-service,classpath:/shared/order-service,classpath:/shared/api-gateway

server: 
  port: 2222
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/  

  


