spring: 
  application: 
    name: user-service
    
server: 
  port: 2222
  
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:1111/eureka/
    healthcheck: 
      enabled: true	# 开启健康检查（需要spring-boot-starter-actuator依赖）
    instance:
      lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）
