spring: 
  application: 
    name: prod-service
  zipkin:
    serviceId: zipkin-server
      
eureka: 
  client: 
    healthcheck: 
      enabled: true	# 开启健康检查（需要spring-boot-starter-actuator依赖）
    instance:
      lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）

#关闭节点状态访问安全验证,生产环境要开启
management: 
  security: 
    enabled: false
    
    
#spring: 
#  activemq: 
#    broker-url: 指定ActiveMQ broker的URL，默认自动生成.
#    in-memory: 是否是内存模式，默认为true.
#    password: 指定broker的密码.
#    pooled: 是否创建PooledConnectionFactory，而非ConnectionFactory，默认false
#    user: 指定broker的用户.