spring: 
  application: 
    name: api-gateway      
      
eureka: 
  client: 
    healthcheck: 
      enabled: false	# 开启健康检查（需要spring-boot-starter-actuator依赖）
    instance:
      lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10    # 续约到期时间（默认90秒）

#关闭节点状态访问安全验证,生产环境要开启
management: 
  security: 
    enabled: false
    
# routes to url

zuul: 
  routes: 
    api-a:  
      path: /api/**
      serviceId: order-service    
